### PR TITLE
Mapbox trpc

### PR DESCRIPTION
**Pull request by DavidOB1**
Closing #1 , replacing axios code with trpc and implementing some abstraction.

### CODE REVIEW

**Review by lukejianu — COMMENTED** [review]
LOOKS GOOD!!!

**Review by devashish9 — APPROVED** [review]
Looks good, documentation is super helpful. Dividing the trpc queries was a good call.

**Comment by dillydally414** [comment]
> LOOKS GOOD!!!
@lukejianu 
Bruh approve it then 😐

**Review by lukejianu — APPROVED** [review]
FINE!!!

**Pull request merged**
